"""add missing indexes for performance

Revision ID: b37af859a415
Revises: 77117bffce57
Create Date: 2026-03-28 12:26:55.321291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37af859a415'
down_revision: Union[str, Sequence[str], None] = '77117bffce57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_printer_slot_events_event_at'), 'printer_slot_events', ['event_at'], unique=False)
    op.create_index(op.f('ix_printer_slot_events_event_type'), 'printer_slot_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_printer_slot_events_printer_id'), 'printer_slot_events', ['printer_id'], unique=False)
    op.create_index(op.f('ix_printer_slot_events_slot_id'), 'printer_slot_events', ['slot_id'], unique=False)
    op.create_index(op.f('ix_printer_slot_events_spool_id'), 'printer_slot_events', ['spool_id'], unique=False)
    op.create_index(op.f('ix_spool_events_device_id'), 'spool_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_spool_events_event_at'), 'spool_events', ['event_at'], unique=False)
    op.create_index(op.f('ix_spool_events_event_type'), 'spool_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_spool_events_spool_id'), 'spool_events', ['spool_id'], unique=False)
    op.create_index(op.f('ix_spool_events_user_id'), 'spool_events', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_api_keys_key_hash'), 'user_api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_user_api_keys_user_id'), 'user_api_keys', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token_hash'), 'user_sessions', ['session_token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_api_keys_user_id'), table_name='user_api_keys')
    op.drop_index(op.f('ix_user_api_keys_key_hash'), table_name='user_api_keys')
    op.drop_index(op.f('ix_spool_events_user_id'), table_name='spool_events')
    op.drop_index(op.f('ix_spool_events_spool_id'), table_name='spool_events')
    op.drop_index(op.f('ix_spool_events_event_type'), table_name='spool_events')
    op.drop_index(op.f('ix_spool_events_event_at'), table_name='spool_events')
    op.drop_index(op.f('ix_spool_events_device_id'), table_name='spool_events')
    op.drop_index(op.f('ix_printer_slot_events_spool_id'), table_name='printer_slot_events')
    op.drop_index(op.f('ix_printer_slot_events_slot_id'), table_name='printer_slot_events')
    op.drop_index(op.f('ix_printer_slot_events_printer_id'), table_name='printer_slot_events')
    op.drop_index(op.f('ix_printer_slot_events_event_type'), table_name='printer_slot_events')
    op.drop_index(op.f('ix_printer_slot_events_event_at'), table_name='printer_slot_events')
    # ### end Alembic commands ###
